repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.7.0  # Use the latest stable version
    hooks:
      - id: black
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 6.1.0  # Use the latest stable version
  #   hooks:
  #     - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1  # Use the latest stable version
    hooks:
      - id: isort